### ISSUE TITLE
Shell/Fret

### ISSUE THREAD

**Issue by matu3ba** [EleanorNB/Vertex#1]
You might want to look for a nicer structured text, which is the standard in all complex production systems.

One could do similar stuff on script execution to define entry-, exit-, and fallback points/values, which are used for human/machine safety. Especially on allocation problems, the shell should keep working.

Though the main problem is that shells are either too incomplete to be very useful (in complex operating systems) or too complex to be verifiable (in terms of control flow doing the right thing).

**Comment by matu3ba** [comment]
The shell should not have PATH at all, because these should be handled by a database with compression and on-demand-caching(bigger systems with enough RAM) and/or csv file(small (sub)systems, statically resolved) <-> hashmap(program,path). Sandboxing is then more or less free, when call paths go via this tool.
Think of namespaces with access permissions on program folders. 

Main problems to fix after/before tool creation are:

1. no csv text file for all compiled artefacts (static/dynamic libs, executables/bundles) defining:
(unique) name, version, upstream_url, publishing_date+time
And packers dont just append these with
(unique) pack_name, pack_version, pack_upstream_url, pack_publishing_date+time
Hence you dont even know, what packers (dont) or separately ship. (I am excluding data, since this is hard to abstract).

2. Semantic with standard where to put things are extremely weak and not tested by CI for packaging. Even nixos cant do this, because there is no proper standard. (Even XDGBDS is not enforced by nudging, ie annotating what software does (not) conform in the CLIs.)

3. The ideal would be computing + writing the call-paths from the host-environment into the binary with no way of the binary to modify it, but this is just a wild dream.

Does this idea sound feasible?

**Comment by EleanorNB** [comment]
I have no idea what you're saying.
